name: Build Android SAI Bundle (.apks)
run-name: ${{ github.event.inputs.repository }} ${{ github.event.inputs.branchName && format('{0}', github.event.inputs.branchName) }} ${{ github.event.inputs.subdir && format('[/{0}]', github.event.inputs.subdir) }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/AndreyPavlenko/Fermata"
      branchName:
        description: "Git branch name [Optional]"
        required: false
        default: ""
      subdir:
        description: "Relative subdirectory path when the project is nested [Optional]"
        required: false
        default: ""
      jdkVersion:
        description: "OpenJDK version: 8, 17, 21, 25, …"
        required: false
        default: "17"
      appIdSuffix:
        description: "Custom App ID Suffix (e.g., .mycustomextension)"
        required: false
        default: ".my.permata.auto.personal.build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: |
          if [[ -z "${{ github.event.inputs.branchName }}" ]]; then
            git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace
          else
            git clone --recurse-submodules --depth=1 --branch ${{ github.event.inputs.branchName }} ${{ github.event.inputs.repository }} workspace
          fi

      - name: Build All Android Modules
        working-directory: ./workspace/${{ github.event.inputs.subdir }}
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleAutoRelease -PAPP_ID_SFX=${{ github.event.inputs.appIdSuffix }} --stacktrace

      - name: Compile and Bundle into SAI APKS File
        run: |
          mkdir -p sai_bundle_package
          
          # 1. Collect only the required 64-bit ARM module files into a clean folder
          find workspace/ -name "*arm64-v8a*.apk" -exec cp {} sai_bundle_package/ \;
          
          # 2. Package all matched .apk binaries directly into a single compressed .apks target file
          cd sai_bundle_package
          zip -r fermata-full-modules.apks ./*.apk
          
          echo "SAI package composition contents:"
          ls -la

      - name: Upload Signed APKS Bundle
        uses: actions/upload-artifact@v4
        with:
          name: fermata-sai-bundle
          path: sai_bundle_package/fermata-full-modules.apks
          retention-days: 1