name: Build Android 64-bit APK
run-name: ${{ github.event.inputs.repository }} ${{ github.event.inputs.branchName && format('{0}', github.event.inputs.branchName) }} ${{ github.event.inputs.subdir && format('[/{0}]', github.event.inputs.subdir) }}

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Git repository URL"
        required: true
        default: "https://github.com/AndreyPavlenko/Fermata"
      branchName:
        description: "Git branch name [Optional]"
        required: false
        default: ""
      subdir:
        description: "Relative subdirectory path when the project is nested [Optional]"
        required: false
        default: ""
      jdkVersion:
        description: "OpenJDK version: 8, 17, 21, 25, …"
        required: false
        default: "17"
      appIdSuffix:
        description: "Custom App ID Suffix (e.g., .mycustomextension)"
        required: false
        default: ".my.permata.auto.personal.build"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ github.event.inputs.jdkVersion }}

      - name: Clone project
        run: |
          if [[ -z "${{ github.event.inputs.branchName }}" ]]; then
            git clone --recurse-submodules --depth=1 ${{ github.event.inputs.repository }} workspace
          else
            git clone --recurse-submodules --depth=1 --branch ${{ github.event.inputs.branchName }} ${{ github.event.inputs.repository }} workspace
          fi

      - name: Build Android APK
        working-directory: ./workspace/${{ github.event.inputs.subdir }}
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          # Changed from bundleAutoRelease to assembleAutoRelease to force APK output creation
          ./gradlew assembleAutoRelease -PAPP_ID_SFX=${{ github.event.inputs.appIdSuffix }} --stacktrace

      - name: Sign 64-bit APK File with P12
        uses: ILAnatoly/sign-android-release@v2
        with:
          releaseDirectory: ${{ github.event.inputs.subdir != '' && format('workspace/{0}/fermata/build/outputs/apk/autoRelease', github.event.inputs.subdir) || 'workspace/fermata/build/outputs/apk/autoRelease' }}
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload Single 64-bit APK
        uses: actions/upload-artifact@v4
        with:
          name: fermata-arm64-installer
          path: ${{ github.event.inputs.subdir != '' && format('workspace/{0}/fermata/build/outputs/apk/autoRelease/*arm64-v8a*.apk', github.event.inputs.subdir) || 'workspace/fermata/build/outputs/apk/autoRelease/*arm64-v8a*.apk' }}
          retention-days: 1